export const CHANGE_SELECTED_CHAT = 'CHANGE_SELECTED_CHAT';

export const GET_CHAT_INFO_REQUEST = 'GET_CHAT_INFO_REQUEST';
export const GET_CHAT_INFO_SUCCESS = 'GET_CHAT_INFO_SUCCESS';
export const GET_CHAT_INFO_FAIL = 'GET_CHAT_INFO_FAIL';

export const LIST_USER_CHATS_REQUEST = 'LIST_USER_CHATS_REQUEST';
export const LIST_USER_CHATS_SUCCESS = 'LIST_USER_CHATS_SUCCESS';
export const LIST_USER_CHATS_FAIL = 'LIST_USER_CHATS_FAIL';

export const LIST_CHAT_MESSAGES_REQUEST = 'LIST_CHAT_MESSAGES_REQUEST';
export const LIST_CHAT_MESSAGES_SUCCESS = 'LIST_CHAT_MESSAGES_SUCCESS';
export const LIST_CHAT_MESSAGES_FAIL = 'LIST_CHAT_MESSAGES_FAIL';
export const CLIENT_UPDATE_MESSAGES = 'CLIENT_UPDATE_MESSAGES';

export const SEND_CHAT_MESSAGE_REQUEST = 'SEND_CHAT_MESSAGE_REQUEST';
export const SEND_CHAT_MESSAGE_SUCCESS = 'SEND_CHAT_MESSAGE_SUCCESS';
export const SEND_CHAT_MESSAGE_FAIL = 'SEND_CHAT_MESSAGE_FAIL';
