export const LIST_COURSES_REQUEST = 'LIST_COURSES_REQUEST';
export const LIST_COURSES_SUCCESS = 'LIST_COURSES_SUCCESS';
export const LIST_COURSES_FAIL = 'LIST_COURSES_FAIL';
export const LIST_COURSES_CLIENT_UPDATE = 'LIST_COURSES_CLIENT_UPDATE';

export const FETCH_COURSE_REQUEST = 'FETCH_COURSE_REQUEST';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSE_FAIL = 'FETCH_COURSE_FAIL';

export const COURSE_CREATE_REQUEST = 'COURSE_CREATE_REQUEST';
export const COURSE_CREATE_SUCCESS = 'COURSE_CREATE_SUCCESS';
export const COURSE_CREATE_FAIL = 'COURSE_CREATE_FAIL';
export const COURSE_CREATE_RESET = 'COURSE_CREATE_RESET';

export const COURSE_DELETE_REQUEST = 'COURSE_DELETE_REQUEST';
export const COURSE_DELETE_SUCCESS = 'COURSE_DELETE_SUCCESS';
export const COURSE_DELETE_FAIL = 'COURSE_DELETE_FAIL';
export const COURSE_DELETE_RESET = 'COURSE_DELETE_RESET';

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST';
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS';
export const COURSE_UPDATE_FAIL = 'COURSE_UPDATE_FAIL';
export const COURSE_UPDATE_RESET = 'COURSE_UPDATE_RESET';
