export const EXAM_CREATE_REQUEST = 'EXAM_CREATE_REQUEST';
export const EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS';
export const EXAM_CREATE_FAIL = 'EXAM_CREATE_FAIL';
export const EXAM_CREATE_RESET = 'EXAM_CREATE_RESET';

export const LIST_STUDENT_EXAMS_REQUEST = 'LIST_STUDENT_EXAMS_REQUEST';
export const LIST_STUDENT_EXAMS_SUCCESS = 'LIST_STUDENT_EXAMS_SUCCESS';
export const LIST_STUDENT_EXAMS_FAIL = 'LIST_STUDENT_EXAMS_FAIL';
export const LIST_STUDENT_EXAMS_RESET = 'LIST_STUDENT_EXAMS_RESET';
