export const LIST_STUDENTS_REQUEST = 'LIST_STUDENTS_REQUEST';
export const LIST_STUDENTS_SUCCESS = 'LIST_STUDENTS_SUCCESS';
export const LIST_STUDENTS_FAIL = 'LIST_STUDENTS_FAIL';

export const STUDENT_CHANGE_GROUP_REQUEST = 'STUDENT_CHANGE_GROUP_REQUEST';
export const STUDENT_CHANGE_GROUP_SUCCESS = 'STUDENT_CHANGE_GROUP_SUCCESS';
export const STUDENT_CHANGE_GROUP_FAIL = 'STUDENT_CHANGE_GROUP_FAIL';
export const STUDENT_CHANGE_GROUP_RESET = 'STUDENT_CHANGE_GROUP_RESET';
