export const LIST_TEACHERS_REQUEST = 'LIST_TEACHERS_REQUEST';
export const LIST_TEACHERS_SUCCESS = 'LIST_TEACHERS_SUCCESS';
export const LIST_TEACHERS_FAIL = 'LIST_TEACHERS_FAIL';

export const LIST_TEACHER_COURSES_REQUEST = 'LIST_TEACHER_COURSES_REQUEST';
export const LIST_TEACHER_COURSES_SUCCESS = 'LIST_TEACHERS_COURSES_SUCCESS';
export const LIST_TEACHER_COURSES_FAIL = 'LIST_TEACHER_COURSES_FAIL';
