export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const VERIFY_TOKEN = 'VERIFY_TOKEN';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_MAKE_ADMIN_REQUEST = 'USER_MAKE_ADMIN_REQUEST';
export const USER_MAKE_ADMIN_SUCCESS = 'USER_MAKE_ADMIN_SUCCESS';
export const USER_MAKE_ADMIN_FAIL = 'USER_MAKE_ADMIN_FAIL';
export const USER_MAKE_ADMIN_RESET = 'USER_MAKE_ADMIN_RESET';
